# Generated by Django 4.0.1 on 2022-03-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_todo_difficulty_todo_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='coin',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
