# Generated by Django 4.0.1 on 2022-03-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='requirement',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='grade',
            field=models.CharField(default='copper', max_length=50),
        ),
    ]
