# Generated by Django 4.0.1 on 2022-02-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Level',
            field=models.IntegerField(default=0),
        ),
    ]
