# Generated by Django 4.0.1 on 2022-02-21 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Level',
            new_name='level',
        ),
    ]
